[project]
name = "homework"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "cognee>=0.2.0",
    "dlt[qdrant]>=1.12.3",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "kuzu>=0.9.0",
    "pandas>=2.3.0",
    "qdrant-client[fastembed]>=1.14.3",
    "requests>=2.32.4",
]
