[project]
name = "rag-agents"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.5",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "markdown>=3.8.2",
    "minsearch>=0.0.4",
    "openai>=1.95.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
]
