[project]
name = "module02"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastembed>=0.7.1",
    "ipykernel>=6.29.5",
    "minsearch>=0.0.3",
    "openai>=1.93.0",
    "pandas>=2.3.0",
    "qdrant-client>=1.14.3",
]
